import { Exercise } from '@/types/workout';

export const DEFAULT_EXERCISES: Exercise[] = [
  // PEITO - BARRA
  {
    id: 'bench-press',
    name: 'Supino Reto',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Deite no banco, pegue a barra com pegada média, abaixe até o peito e empurre para cima.',
  },
  {
    id: 'incline-bench',
    name: 'Supino Inclinado',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Banco inclinado a 30-45 graus, pegue a barra e pressione para cima.',
  },
  {
    id: 'decline-bench',
    name: 'Supino Declinado',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Banco declinado, pegue a barra e pressione para cima.',
  },
  {
    id: 'close-grip-bench',
    name: 'Supino Pegada Fechada',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Pegada fechada na barra, foco no tríceps e peito interno.',
  },
  {
    id: 'smith-bench',
    name: 'Supino em Máquina Smith',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Supino na máquina Smith com guia fixo.',
  },
  // PEITO - HALTERES
  {
    id: 'dumbbell-bench',
    name: 'Supino Reto com Halteres',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Deite no banco, empurre halteres para cima.',
  },
  {
    id: 'dumbbell-incline',
    name: 'Supino Inclinado com Halteres',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Banco inclinado, empurre halteres para cima.',
  },
  {
    id: 'dumbbell-decline',
    name: 'Supino Declinado com Halteres',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Banco declinado, empurre halteres para cima.',
  },
  {
    id: 'dumbbell-fly',
    name: 'Crucifixo Reto',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Com halteres, abra os braços em arco e depois junte.',
  },
  {
    id: 'incline-fly',
    name: 'Crucifixo Inclinado',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Banco inclinado, abra os braços em arco com halteres.',
  },
  {
    id: 'pullover',
    name: 'Pullover',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Deitado, passe halter por trás da cabeça em arco.',
  },
  // PEITO - MÁQUINAS
  {
    id: 'peck-deck',
    name: 'Peck Deck (Fly Machine)',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Sentado na máquina, abra e feche os braços.',
  },
  {
    id: 'vertical-press',
    name: 'Supino Máquina (Vertical)',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Máquina vertical, empurre para frente.',
  },
  {
    id: 'horizontal-press',
    name: 'Supino Máquina (Horizontal)',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Máquina horizontal, empurre para frente.',
  },
  {
    id: 'crossover-machine',
    name: 'Crossover Máquina',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Na máquina crossover, cruze os braços na frente.',
  },
  {
    id: 'machine-fly',
    name: 'Crucifixo na Máquina',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Na máquina, abra e feche os braços.',
  },
  // PEITO - CABO
  {
    id: 'cable-crossover-high',
    name: 'Crossover Alto',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Polias altas, cruze os braços na frente.',
  },
  {
    id: 'cable-crossover-mid',
    name: 'Crossover Médio',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Polias na altura do peito, cruze os braços.',
  },
  {
    id: 'cable-crossover-low',
    name: 'Crossover Baixo',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Polias baixas, cruze os braços para cima.',
  },
  {
    id: 'incline-cable-fly',
    name: 'Crucifixo no Cabo Inclinado',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Banco inclinado, abra os braços com cabos.',
  },
  {
    id: 'cable-press',
    name: 'Press no Cabo',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Empurre os cabos para frente.',
  },
  // PEITO - PESO CORPORAL
  {
    id: 'push-up',
    name: 'Flexão de Braço',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Em prancha, abaixe o corpo e empurre para cima.',
  },
  {
    id: 'decline-push-up',
    name: 'Flexão Declinada',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Pés elevados, faça flexão.',
  },
  {
    id: 'incline-push-up',
    name: 'Flexão Inclinada',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Mãos elevadas, faça flexão.',
  },
  {
    id: 'diamond-push-up',
    name: 'Flexão com Pegada Fechada',
    muscleGroup: 'chest',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Mãos em formato de diamante, faça flexão.',
  },
  // COSTAS - BARRA
  {
    id: 'pull-up-pronada',
    name: 'Barra Fixa (Pronada)',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Pegada pronada, puxe o corpo para cima.',
  },
  {
    id: 'pull-up-supinada',
    name: 'Barra Fixa (Supinada)',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Pegada supinada, puxe o corpo para cima.',
  },
  {
    id: 'pull-up-neutra',
    name: 'Barra Fixa (Neutra)',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Pegada neutra, puxe o corpo para cima.',
  },
  {
    id: 'barbell-row',
    name: 'Remada Curvada',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Curvado para frente, puxe a barra em direção ao abdômen.',
  },
  {
    id: 't-bar-row',
    name: 'Remada Cavalinho (T-bar)',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Na máquina T-bar, puxe a barra em direção ao peito.',
  },
  {
    id: 'deadlift',
    name: 'Levantamento Terra (Deadlift)',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Pegue a barra do chão e levante até a posição ereta.',
  },
  {
    id: 'pendlay-row',
    name: 'Remada Pendlay',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Barra no chão, puxe explosivamente até o abdômen.',
  },
  {
    id: 'rack-pull',
    name: 'Rack Pull',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Barra no rack, puxe de altura média até a posição ereta.',
  },
  // COSTAS - HALTERES
  {
    id: 'one-arm-row',
    name: 'Remada Unilateral',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Apoiado no banco, puxe halter unilateralmente.',
  },
  {
    id: 'dumbbell-row',
    name: 'Remada Curvada com Dois Halteres',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Curvado, puxe halteres simultaneamente.',
  },
  {
    id: 'dumbbell-pullover',
    name: 'Pullover',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Deitado, passe halter por trás da cabeça.',
  },
  {
    id: 'shrugs',
    name: 'Encolhimento',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Em pé, eleve os ombros com halteres.',
  },
  // COSTAS - MÁQUINAS
  {
    id: 'lat-pulldown',
    name: 'Puxada Alta Máquina (Pulldown)',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Puxe a barra para baixo em direção ao peito.',
  },
  {
    id: 'seated-cable-row',
    name: 'Remada Baixa Máquina',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Sentado, puxe o cabo em direção ao abdômen.',
  },
  {
    id: 'high-row-machine',
    name: 'Remada Alta Máquina',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Na máquina, puxe para cima em direção ao peito.',
  },
  {
    id: 'chest-supported-row',
    name: 'Remada Articulada',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Apoiado no peito, puxe os braços para trás.',
  },
  {
    id: 'machine-pullover',
    name: 'Pull-over Máquina',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Na máquina, puxe de cima para baixo.',
  },
  // COSTAS - CABOS
  {
    id: 'cable-pulldown',
    name: 'Pulldown',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Puxe o cabo para baixo em direção ao peito.',
  },
  {
    id: 'cable-row',
    name: 'Remada Baixa',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Puxe o cabo em direção ao abdômen.',
  },
  {
    id: 'one-arm-cable-row',
    name: 'Remada Unilateral no Cabo',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Puxe o cabo unilateralmente.',
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Puxe o cabo em direção ao rosto.',
  },
  {
    id: 'straight-arm-pulldown',
    name: 'Straight Arm Pulldown',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Braços estendidos, puxe o cabo para baixo.',
  },
  // COSTAS - PESO CORPORAL
  {
    id: 'pull-up',
    name: 'Barra Fixa',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Puxe o corpo para cima até o queixo passar da barra.',
  },
  {
    id: 'australian-pull-up',
    name: 'Australian Pull-up',
    muscleGroup: 'back',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Barra baixa, puxe o corpo horizontalmente.',
  },
  // BÍCEPS - BARRA
  {
    id: 'barbell-curl',
    name: 'Rosca Direta',
    muscleGroup: 'biceps',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Flexione os cotovelos trazendo a barra em direção aos ombros.',
  },
  {
    id: 'wide-grip-curl',
    name: 'Rosca Direta Pegada Aberta',
    muscleGroup: 'biceps',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Pegada aberta, flexione os cotovelos.',
  },
  {
    id: 'close-grip-curl',
    name: 'Rosca Direta Pegada Fechada',
    muscleGroup: 'biceps',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Pegada fechada, flexione os cotovelos.',
  },
  {
    id: 'preacher-curl-bar',
    name: 'Rosca Scott Barra',
    muscleGroup: 'biceps',
    isCustom: false,
    equipment: 'barra',
    instructions: 'No banco scott, flexione os cotovelos com barra.',
  },
  {
    id: 'reverse-curl',
    name: 'Rosca Invertida',
    muscleGroup: 'biceps',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Pegada invertida, flexione os cotovelos.',
  },
  {
    id: '21-curl',
    name: 'Rosca 21',
    muscleGroup: 'biceps',
    isCustom: false,
    equipment: 'barra',
    instructions: '7 repetições parciais inferior, 7 parciais superior, 7 completas.',
  },
  // BÍCEPS - HALTERES
  {
    id: 'alternating-curl',
    name: 'Rosca Alternada',
    muscleGroup: 'biceps',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Flexione os cotovelos alternadamente.',
  },
  {
    id: 'simultaneous-curl',
    name: 'Rosca Simultânea',
    muscleGroup: 'biceps',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Flexione os cotovelos simultaneamente.',
  },
  {
    id: 'hammer-curl',
    name: 'Rosca Martelo',
    muscleGroup: 'biceps',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Rosca com pegada neutra (palmas se olhando).',
  },
  {
    id: 'concentration-curl',
    name: 'Rosca Concentrada',
    muscleGroup: 'biceps',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Sentado, apoiado no joelho, flexione o cotovelo.',
  },
  {
    id: 'incline-curl',
    name: 'Rosca Inclinado no Banco',
    muscleGroup: 'biceps',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Banco inclinado, flexione os cotovelos.',
  },
  {
    id: 'cross-body-curl',
    name: 'Rosca Cross-body',
    muscleGroup: 'biceps',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Flexione o cotovelo cruzando o corpo.',
  },
  // BÍCEPS - MÁQUINAS
  {
    id: 'bicep-machine',
    name: 'Rosca Bíceps Máquina',
    muscleGroup: 'biceps',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Na máquina, flexione os cotovelos.',
  },
  {
    id: 'preacher-machine',
    name: 'Rosca Scott Máquina',
    muscleGroup: 'biceps',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Na máquina scott, flexione os cotovelos.',
  },
  // BÍCEPS - CABOS
  {
    id: 'cable-curl-low',
    name: 'Rosca no Cabo Baixo',
    muscleGroup: 'biceps',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Polia baixa, flexione os cotovelos.',
  },
  {
    id: 'cable-curl-high',
    name: 'Rosca no Cabo Alto',
    muscleGroup: 'biceps',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Polia alta, flexione os cotovelos.',
  },
  {
    id: 'cable-hammer-curl',
    name: 'Rosca Martelo no Cabo',
    muscleGroup: 'biceps',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Pegada neutra no cabo, flexione os cotovelos.',
  },
  {
    id: 'one-arm-cable-curl',
    name: 'Rosca Unilateral Cabo',
    muscleGroup: 'biceps',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Unilateralmente, flexione o cotovelo no cabo.',
  },
  // TRÍCEPS - BARRA
  {
    id: 'overhead-extension',
    name: 'Tríceps Testa Barra',
    muscleGroup: 'triceps',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Acima da cabeça, estenda os braços com barra.',
  },
  {
    id: 'french-press',
    name: 'Tríceps Francês',
    muscleGroup: 'triceps',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Deitado, estenda os braços acima da cabeça.',
  },
  {
    id: 'weighted-dips',
    name: 'Paralelas com Peso',
    muscleGroup: 'triceps',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Nas paralelas com peso, abaixe e suba o corpo.',
  },
  // TRÍCEPS - HALTERES
  {
    id: 'one-arm-overhead',
    name: 'Tríceps Francês Unilateral',
    muscleGroup: 'triceps',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Acima da cabeça, estenda um braço por vez.',
  },
  {
    id: 'two-arm-overhead',
    name: 'Tríceps Francês Bilateral',
    muscleGroup: 'triceps',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Acima da cabeça, estenda ambos os braços.',
  },
  {
    id: 'tricep-kickback',
    name: 'Tríceps Kickback',
    muscleGroup: 'triceps',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Curvado, estenda o braço para trás.',
  },
  {
    id: 'tricep-coice',
    name: 'Tríceps Coice',
    muscleGroup: 'triceps',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Apoiado, estenda o braço para trás.',
  },
  // TRÍCEPS - MÁQUINAS
  {
    id: 'tricep-machine',
    name: 'Tríceps Máquina',
    muscleGroup: 'triceps',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Na máquina, estenda os braços.',
  },
  {
    id: 'assisted-dips',
    name: 'Paralelas Assistidas',
    muscleGroup: 'triceps',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Nas paralelas assistidas, abaixe e suba.',
  },
  // TRÍCEPS - CABOS
  {
    id: 'tricep-pushdown',
    name: 'Tríceps Pulley Corda',
    muscleGroup: 'triceps',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Polia alta, empurre a corda para baixo.',
  },
  {
    id: 'tricep-pushdown-bar',
    name: 'Tríceps Pulley Barra',
    muscleGroup: 'triceps',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Polia alta, empurre a barra para baixo.',
  },
  {
    id: 'cable-overhead',
    name: 'Tríceps Testa no Cabo',
    muscleGroup: 'triceps',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Polia baixa, estenda os braços acima da cabeça.',
  },
  {
    id: 'cable-inverted',
    name: 'Tríceps Invertido no Cabo',
    muscleGroup: 'triceps',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Polia baixa, estenda os braços para cima.',
  },
  {
    id: 'one-arm-cable-extension',
    name: 'Extensão Unilateral no Cabo',
    muscleGroup: 'triceps',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Unilateralmente, estenda o braço no cabo.',
  },
  // TRÍCEPS - PESO CORPORAL
  {
    id: 'tricep-dips',
    name: 'Mergulho nas Paralelas',
    muscleGroup: 'triceps',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Apoiado nas barras, abaixe e suba o corpo.',
  },
  {
    id: 'bench-dips',
    name: 'Mergulho no Banco',
    muscleGroup: 'triceps',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Apoiado no banco, abaixe e suba o corpo.',
  },
  // OMBROS - BARRA
  {
    id: 'military-press',
    name: 'Desenvolvimento Militar',
    muscleGroup: 'shoulders',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Em pé, empurre a barra acima da cabeça.',
  },
  {
    id: 'behind-neck-press',
    name: 'Desenvolvimento Atrás da Nuca',
    muscleGroup: 'shoulders',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Empurre a barra atrás da nuca.',
  },
  {
    id: 'upright-row',
    name: 'Remada Alta',
    muscleGroup: 'shoulders',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Puxe a barra em direção ao queixo.',
  },
  {
    id: 'front-raise-bar',
    name: 'Elevação Frontal Barra',
    muscleGroup: 'shoulders',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Levante a barra à frente até a altura dos ombros.',
  },
  // OMBROS - HALTERES
  {
    id: 'seated-shoulder-press',
    name: 'Desenvolvimento Sentado',
    muscleGroup: 'shoulders',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Sentado, empurre halteres acima da cabeça.',
  },
  {
    id: 'standing-shoulder-press',
    name: 'Desenvolvimento em Pé',
    muscleGroup: 'shoulders',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Em pé, empurre halteres acima da cabeça.',
  },
  {
    id: 'lateral-raise',
    name: 'Elevação Lateral',
    muscleGroup: 'shoulders',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Levante halteres lateralmente até a altura dos ombros.',
  },
  {
    id: 'front-raise',
    name: 'Elevação Frontal',
    muscleGroup: 'shoulders',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Levante halteres à frente até a altura dos ombros.',
  },
  {
    id: 'rear-delt-fly',
    name: 'Elevação Posterior (Reverse Fly)',
    muscleGroup: 'shoulders',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Curvado, abra os braços lateralmente.',
  },
  {
    id: 'arnold-press',
    name: 'Arnold Press',
    muscleGroup: 'shoulders',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Rotacione os halteres enquanto empurra para cima.',
  },
  // OMBROS - MÁQUINAS
  {
    id: 'shoulder-press-machine',
    name: 'Desenvolvimento Máquina',
    muscleGroup: 'shoulders',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Na máquina, empurre para cima.',
  },
  {
    id: 'lateral-raise-machine',
    name: 'Elevação Lateral Máquina',
    muscleGroup: 'shoulders',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Na máquina, eleve lateralmente.',
  },
  {
    id: 'reverse-peck-deck',
    name: 'Peck Deck Invertido',
    muscleGroup: 'shoulders',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Na máquina invertida, abra os braços.',
  },
  // OMBROS - CABOS
  {
    id: 'cable-lateral-raise',
    name: 'Elevação Lateral Cabo',
    muscleGroup: 'shoulders',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Polia baixa, eleve lateralmente.',
  },
  {
    id: 'cable-front-raise',
    name: 'Elevação Frontal Cabo',
    muscleGroup: 'shoulders',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Polia baixa, eleve à frente.',
  },
  {
    id: 'cable-reverse-fly',
    name: 'Crucifixo Invertido Cabo',
    muscleGroup: 'shoulders',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Polia à frente, abra os braços.',
  },
  {
    id: 'cable-shoulder-press',
    name: 'Desenvolvimento no Cabo',
    muscleGroup: 'shoulders',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Polia baixa, empurre para cima.',
  },
  // PERNAS - QUADRÍCEPS - BARRA
  {
    id: 'squat',
    name: 'Agachamento Livre',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Barra nas costas, agache até coxas paralelas ao chão.',
  },
  {
    id: 'front-squat',
    name: 'Front Squat',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Barra na frente, agache até coxas paralelas.',
  },
  {
    id: 'bulgarian-squat',
    name: 'Agachamento Búlgaro com Barra',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Pé traseiro elevado, agache com barra.',
  },
  {
    id: 'hack-squat',
    name: 'Agachamento Hack Livre',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Barra atrás das pernas, agache.',
  },
  // PERNAS - QUADRÍCEPS - HALTERES
  {
    id: 'dumbbell-squat',
    name: 'Agachamento Halteres',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Com halteres, agache até coxas paralelas.',
  },
  {
    id: 'lunge',
    name: 'Avanço (Lunge)',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Dê um passo à frente e abaixe o corpo.',
  },
  {
    id: 'walking-lunge',
    name: 'Passada',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Caminhe fazendo afundos alternados.',
  },
  {
    id: 'reverse-lunge',
    name: 'Afundo',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Dê um passo para trás e abaixe o corpo.',
  },
  // PERNAS - QUADRÍCEPS - MÁQUINAS
  {
    id: 'leg-press-45',
    name: 'Leg Press 45°',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Sentado, empurre a plataforma em 45 graus.',
  },
  {
    id: 'leg-press-horizontal',
    name: 'Leg Press Horizontal',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Sentado, empurre a plataforma horizontalmente.',
  },
  {
    id: 'hack-machine',
    name: 'Hack Machine',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Na máquina hack, agache.',
  },
  {
    id: 'leg-extension',
    name: 'Cadeira Extensora',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Sentado, estenda as pernas para cima.',
  },
  // PERNAS - QUADRÍCEPS - CABOS
  {
    id: 'cable-extension',
    name: 'Extensão no Cabo',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Polia baixa, estenda a perna.',
  },
  // PERNAS - QUADRÍCEPS - PESO CORPORAL
  {
    id: 'bodyweight-squat',
    name: 'Agachamento Livre',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Sem peso, agache até coxas paralelas.',
  },
  {
    id: 'sumo-squat',
    name: 'Agachamento Sumô',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Pernas abertas, agache.',
  },
  {
    id: 'pistol-squat',
    name: 'Agachamento Pistol',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Uma perna, agache completamente.',
  },
  // PERNAS - POSTERIOR - BARRA
  {
    id: 'stiff',
    name: 'Stiff',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Pernas estendidas, flexione o tronco com barra.',
  },
  {
    id: 'romanian-deadlift',
    name: 'Terra Romeno',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Flexione o tronco mantendo pernas levemente flexionadas.',
  },
  {
    id: 'good-morning',
    name: 'Bom Dia',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Barra nas costas, flexione o tronco para frente.',
  },
  // PERNAS - POSTERIOR - HALTERES
  {
    id: 'dumbbell-stiff',
    name: 'Stiff com Halteres',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Pernas estendidas, flexione o tronco com halteres.',
  },
  {
    id: 'one-leg-curl',
    name: 'Flexão Unilateral Halter',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Uma perna, flexione o joelho com halter.',
  },
  // PERNAS - POSTERIOR - MÁQUINAS
  {
    id: 'lying-leg-curl',
    name: 'Mesa Flexora',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Deitado, flexione as pernas.',
  },
  {
    id: 'seated-leg-curl',
    name: 'Cadeira Flexora',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Sentado, flexione as pernas.',
  },
  {
    id: 'stiff-machine',
    name: 'Stiff Máquina',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Na máquina, flexione o tronco.',
  },
  // PERNAS - POSTERIOR - CABOS
  {
    id: 'standing-leg-curl',
    name: 'Flexora em Pé no Cabo',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Em pé, flexione a perna no cabo.',
  },
  // GLÚTEOS - BARRA
  {
    id: 'sumo-deadlift',
    name: 'Levantamento Terra Sumô',
    muscleGroup: 'glutes',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Pernas abertas, levante a barra.',
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrust Barra',
    muscleGroup: 'glutes',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Apoiado em banco, eleve o quadril com barra.',
  },
  {
    id: 'sumo-squat-bar',
    name: 'Agachamento Sumô',
    muscleGroup: 'glutes',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Pernas abertas, agache com barra.',
  },
  // GLÚTEOS - HALTERES
  {
    id: 'dumbbell-lunge',
    name: 'Afundo',
    muscleGroup: 'glutes',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Dê um passo à frente e abaixe o corpo.',
  },
  {
    id: 'dumbbell-walking-lunge',
    name: 'Passada',
    muscleGroup: 'glutes',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Caminhe fazendo afundos alternados.',
  },
  {
    id: 'hip-thrust-dumbbell',
    name: 'Elevação Pélvica com Halter',
    muscleGroup: 'glutes',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Apoiado, eleve o quadril com halter.',
  },
  // GLÚTEOS - MÁQUINAS
  {
    id: 'glute-machine',
    name: 'Glúteo Máquina',
    muscleGroup: 'glutes',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Na máquina, empurre com as pernas.',
  },
  {
    id: 'abduction-machine',
    name: 'Abdução Máquina',
    muscleGroup: 'glutes',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Na máquina, abra as pernas.',
  },
  {
    id: 'smith-squat',
    name: 'Smith Machine (Agachamentos e Avanços)',
    muscleGroup: 'glutes',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Na Smith, faça agachamentos ou avanços.',
  },
  // GLÚTEOS - CABOS
  {
    id: 'cable-kickback',
    name: 'Coice no Cabo',
    muscleGroup: 'glutes',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Polia baixa, chute a perna para trás.',
  },
  {
    id: 'cable-abduction',
    name: 'Abdução no Cabo',
    muscleGroup: 'glutes',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Polia baixa, abra a perna lateralmente.',
  },
  {
    id: 'hip-extension-cable',
    name: 'Extensão de Quadril',
    muscleGroup: 'glutes',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Polia baixa, estenda o quadril.',
  },
  // GLÚTEOS - PESO CORPORAL
  {
    id: 'glute-bridge',
    name: 'Ponte de Glúteo',
    muscleGroup: 'glutes',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Deitado, eleve o quadril.',
  },
  {
    id: 'lateral-abduction',
    name: 'Abdução Lateral',
    muscleGroup: 'glutes',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Deitado de lado, eleve a perna.',
  },
  // PANTURRILHA
  {
    id: 'standing-calf-raise',
    name: 'Elevação de Panturrilha em Pé',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Em pé, levante os calcanhares do chão.',
  },
  {
    id: 'seated-calf-raise',
    name: 'Elevação de Panturrilha Sentado',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Sentado, levante os calcanhares.',
  },
  {
    id: 'calf-press',
    name: 'Panturrilha no Leg Press',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'No leg press, levante os calcanhares.',
  },
  {
    id: 'smith-calf',
    name: 'Panturrilha no Smith',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'No Smith, levante os calcanhares.',
  },
  {
    id: 'step-calf',
    name: 'Panturrilha no Step',
    muscleGroup: 'legs',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'No step, levante os calcanhares.',
  },
  // CORE - PESO CORPORAL
  {
    id: 'plank',
    name: 'Prancha',
    muscleGroup: 'core',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Mantenha posição de prancha com corpo reto.',
  },
  {
    id: 'side-plank',
    name: 'Prancha Lateral',
    muscleGroup: 'core',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'De lado, mantenha posição de prancha.',
  },
  {
    id: 'leg-raise',
    name: 'Elevação de Pernas',
    muscleGroup: 'core',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Deitado, eleve as pernas.',
  },
  {
    id: 'crunches',
    name: 'Abdominal Supra',
    muscleGroup: 'core',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Deitado, flexione o tronco em direção aos joelhos.',
  },
  {
    id: 'reverse-crunch',
    name: 'Abdominal Infra',
    muscleGroup: 'core',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Deitado, eleve os joelhos em direção ao peito.',
  },
  {
    id: 'bicycle-crunch',
    name: 'Bicicleta',
    muscleGroup: 'core',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Deitado, simule pedalar no ar.',
  },
  {
    id: 'v-sit',
    name: 'Abdominal V',
    muscleGroup: 'core',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Sentado, forme um V com tronco e pernas.',
  },
  {
    id: 'jackknife',
    name: 'Abdominal Canivete',
    muscleGroup: 'core',
    isCustom: false,
    equipment: 'peso-corporal',
    instructions: 'Deitado, junte tronco e pernas simultaneamente.',
  },
  // CORE - MÁQUINAS
  {
    id: 'ab-machine',
    name: 'Abdominal Máquina',
    muscleGroup: 'core',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Na máquina, flexione o tronco.',
  },
  {
    id: 'plank-machine',
    name: 'Prancha Abdominal Máquina',
    muscleGroup: 'core',
    isCustom: false,
    equipment: 'maquina',
    instructions: 'Na máquina, mantenha prancha.',
  },
  // CORE - CABOS
  {
    id: 'cable-crunch',
    name: 'Abdominal no Cabo (Crunch)',
    muscleGroup: 'core',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Polia alta, flexione o tronco.',
  },
  {
    id: 'kneeling-cable-crunch',
    name: 'Ab Crunch Ajoelhado',
    muscleGroup: 'core',
    isCustom: false,
    equipment: 'cabo',
    instructions: 'Ajoelhado, flexione o tronco no cabo.',
  },
  // CORE - HALTER/BARRA
  {
    id: 'ab-wheel',
    name: 'Ab Wheel (Rodinha)',
    muscleGroup: 'core',
    isCustom: false,
    equipment: 'barra',
    instructions: 'Com rodinha, role para frente e volte.',
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    muscleGroup: 'core',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Sentado, gire o tronco de um lado para outro com peso.',
  },
  {
    id: 'heavy-one-arm-row',
    name: 'Remada Unilateral Pesada (Core Anti-rotação)',
    muscleGroup: 'core',
    isCustom: false,
    equipment: 'halteres',
    instructions: 'Remada unilateral pesada para fortalecer core.',
  },
];
